# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/xavier/Desktop/Research/Projects/HAB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/xavier/Desktop/Research/Projects/HAB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/xavier/Desktop/Research/Projects/HAB/CMakeFiles /Users/xavier/Desktop/Research/Projects/HAB/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/xavier/Desktop/Research/Projects/HAB/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
CMakeFiles/Tpca.dir/rule:
	$(MAKE) -f CMakeFiles/Makefile2 CMakeFiles/Tpca.dir/rule
.PHONY : CMakeFiles/Tpca.dir/rule

# Convenience name for target.
Tpca: CMakeFiles/Tpca.dir/rule

.PHONY : Tpca

# fast build rule for target.
Tpca/fast:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/build
.PHONY : Tpca/fast

# Convenience name for target.
CMakeFiles/GeodesicShooting.dir/rule:
	$(MAKE) -f CMakeFiles/Makefile2 CMakeFiles/GeodesicShooting.dir/rule
.PHONY : CMakeFiles/GeodesicShooting.dir/rule

# Convenience name for target.
GeodesicShooting: CMakeFiles/GeodesicShooting.dir/rule

.PHONY : GeodesicShooting

# fast build rule for target.
GeodesicShooting/fast:
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/build
.PHONY : GeodesicShooting/fast

Alg/GeodesicShooting.o: Alg/GeodesicShooting.cxx.o

.PHONY : Alg/GeodesicShooting.o

# target to build an object file
Alg/GeodesicShooting.cxx.o:
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Alg/GeodesicShooting.cxx.o
.PHONY : Alg/GeodesicShooting.cxx.o

Alg/GeodesicShooting.i: Alg/GeodesicShooting.cxx.i

.PHONY : Alg/GeodesicShooting.i

# target to preprocess a source file
Alg/GeodesicShooting.cxx.i:
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Alg/GeodesicShooting.cxx.i
.PHONY : Alg/GeodesicShooting.cxx.i

Alg/GeodesicShooting.s: Alg/GeodesicShooting.cxx.s

.PHONY : Alg/GeodesicShooting.s

# target to generate assembly for a file
Alg/GeodesicShooting.cxx.s:
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Alg/GeodesicShooting.cxx.s
.PHONY : Alg/GeodesicShooting.cxx.s

Alg/Tpca.o: Alg/Tpca.cxx.o

.PHONY : Alg/Tpca.o

# target to build an object file
Alg/Tpca.cxx.o:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Alg/Tpca.cxx.o
.PHONY : Alg/Tpca.cxx.o

Alg/Tpca.i: Alg/Tpca.cxx.i

.PHONY : Alg/Tpca.i

# target to preprocess a source file
Alg/Tpca.cxx.i:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Alg/Tpca.cxx.i
.PHONY : Alg/Tpca.cxx.i

Alg/Tpca.s: Alg/Tpca.cxx.s

.PHONY : Alg/Tpca.s

# target to generate assembly for a file
Alg/Tpca.cxx.s:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Alg/Tpca.cxx.s
.PHONY : Alg/Tpca.cxx.s

Base/Armalib.o: Base/Armalib.cxx.o

.PHONY : Base/Armalib.o

# target to build an object file
Base/Armalib.cxx.o:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Base/Armalib.cxx.o
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Base/Armalib.cxx.o
.PHONY : Base/Armalib.cxx.o

Base/Armalib.i: Base/Armalib.cxx.i

.PHONY : Base/Armalib.i

# target to preprocess a source file
Base/Armalib.cxx.i:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Base/Armalib.cxx.i
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Base/Armalib.cxx.i
.PHONY : Base/Armalib.cxx.i

Base/Armalib.s: Base/Armalib.cxx.s

.PHONY : Base/Armalib.s

# target to generate assembly for a file
Base/Armalib.cxx.s:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Base/Armalib.cxx.s
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Base/Armalib.cxx.s
.PHONY : Base/Armalib.cxx.s

Base/FftOper.o: Base/FftOper.cxx.o

.PHONY : Base/FftOper.o

# target to build an object file
Base/FftOper.cxx.o:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Base/FftOper.cxx.o
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Base/FftOper.cxx.o
.PHONY : Base/FftOper.cxx.o

Base/FftOper.i: Base/FftOper.cxx.i

.PHONY : Base/FftOper.i

# target to preprocess a source file
Base/FftOper.cxx.i:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Base/FftOper.cxx.i
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Base/FftOper.cxx.i
.PHONY : Base/FftOper.cxx.i

Base/FftOper.s: Base/FftOper.cxx.s

.PHONY : Base/FftOper.s

# target to generate assembly for a file
Base/FftOper.cxx.s:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Base/FftOper.cxx.s
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Base/FftOper.cxx.s
.PHONY : Base/FftOper.cxx.s

Base/FieldComplex3D.o: Base/FieldComplex3D.cxx.o

.PHONY : Base/FieldComplex3D.o

# target to build an object file
Base/FieldComplex3D.cxx.o:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Base/FieldComplex3D.cxx.o
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Base/FieldComplex3D.cxx.o
.PHONY : Base/FieldComplex3D.cxx.o

Base/FieldComplex3D.i: Base/FieldComplex3D.cxx.i

.PHONY : Base/FieldComplex3D.i

# target to preprocess a source file
Base/FieldComplex3D.cxx.i:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Base/FieldComplex3D.cxx.i
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Base/FieldComplex3D.cxx.i
.PHONY : Base/FieldComplex3D.cxx.i

Base/FieldComplex3D.s: Base/FieldComplex3D.cxx.s

.PHONY : Base/FieldComplex3D.s

# target to generate assembly for a file
Base/FieldComplex3D.cxx.s:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Base/FieldComplex3D.cxx.s
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Base/FieldComplex3D.cxx.s
.PHONY : Base/FieldComplex3D.cxx.s

Base/MPIlib.o: Base/MPIlib.cxx.o

.PHONY : Base/MPIlib.o

# target to build an object file
Base/MPIlib.cxx.o:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Base/MPIlib.cxx.o
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Base/MPIlib.cxx.o
.PHONY : Base/MPIlib.cxx.o

Base/MPIlib.i: Base/MPIlib.cxx.i

.PHONY : Base/MPIlib.i

# target to preprocess a source file
Base/MPIlib.cxx.i:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Base/MPIlib.cxx.i
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Base/MPIlib.cxx.i
.PHONY : Base/MPIlib.cxx.i

Base/MPIlib.s: Base/MPIlib.cxx.s

.PHONY : Base/MPIlib.s

# target to generate assembly for a file
Base/MPIlib.cxx.s:
	$(MAKE) -f CMakeFiles/Tpca.dir/build.make CMakeFiles/Tpca.dir/Base/MPIlib.cxx.s
	$(MAKE) -f CMakeFiles/GeodesicShooting.dir/build.make CMakeFiles/GeodesicShooting.dir/Base/MPIlib.cxx.s
.PHONY : Base/MPIlib.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Tpca"
	@echo "... GeodesicShooting"
	@echo "... Alg/GeodesicShooting.o"
	@echo "... Alg/GeodesicShooting.i"
	@echo "... Alg/GeodesicShooting.s"
	@echo "... Alg/Tpca.o"
	@echo "... Alg/Tpca.i"
	@echo "... Alg/Tpca.s"
	@echo "... Base/Armalib.o"
	@echo "... Base/Armalib.i"
	@echo "... Base/Armalib.s"
	@echo "... Base/FftOper.o"
	@echo "... Base/FftOper.i"
	@echo "... Base/FftOper.s"
	@echo "... Base/FieldComplex3D.o"
	@echo "... Base/FieldComplex3D.i"
	@echo "... Base/FieldComplex3D.s"
	@echo "... Base/MPIlib.o"
	@echo "... Base/MPIlib.i"
	@echo "... Base/MPIlib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

